# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - init: |
      python3.8.15 -m pip install --upgrade pip
      python3.8.15 -m pip install -r requirements.txt
    command: python3.8.15 app.py  # Assuming your main Python script is named app.py

image:
  file: .gitpod.Dockerfile
